### ISSUE TITLE
error display with France

### ISSUE THREAD

**Issue by chassain** [mykle1/MMM-ISS#10]
Hello mykle,

i have an error with my configuration
country : France
city : Toulon
no region state

this city is on the site Nasa spot the station...
When i don't put parameters of city and country but only lat and lng i have chicaco Illinois :)

`		{
			disabled: false,
       			module: 'MMM-ISS',
       			position: 'center',
	   		config: {
		   		lat: "43.124228",                              // latitude
		   		lng: "5.928",                             // longitude
		   		units: "km",                               // mi = miles, mph / km = kilometers, km/h
		   		useHeader: false,                          // true if you want a header      
		   		header: "",                                // Any text you want. useHeader must be true
		   		updateInterval: 60 * 1000,
				}
		},
`
Thanks

**Comment by chassain** [comment]
Sorry..it's ok ...with state none !! Yes..great module...See you on magicmirror forum

**Comment by mykle1** [comment]
Thank you bro!
