### ISSUE TITLE
Appliaction flashes every 3 seconds when carousel suspends modules

### ISSUE THREAD

**Issue by ghost** [mykle1/MMM-ISS#12]
kind of annoying, not sure how to fix it myself, any ideas?

edit - moving it into this format instead of this one seems to have worked

                        //{carousel2Id: "6",name:'MMM-ISS', position:'top_left'},

                        'MMM-NewsFeedTicker', 'MMM-ISS',

**Comment by mykle1** [comment]
Glad you found a solution. Sometimes modules don't always play nice together.

**Comment by ghost** [comment]
> 
> 
> Glad you found a solution. Sometimes modules don't always play nice together.

by the way, thank you for doing all this work with these modules im trying to get my foot in the door and learn programming myself, you do very clean work i notice already, if you are in the magicmirror discord id probably want to ask you a few questions in the future if possible, i really appreciate what you do
