### ISSUE TITLE
Error Found (for cities outside the US)

### ISSUE THREAD

**Issue by E3V3A** [mykle1/MMM-ISS#6]
The Widget give an error for cities with unknown `regions`. In those cities, try to use:  
`regionState: "None",` in your config. 

You can check your city [here](https://spotthestation.nasa.gov/widget/). 

![firefox_2018-03-04_22-27-32](https://user-images.githubusercontent.com/194392/36950208-50a72baa-1ffb-11e8-9a94-847391d3131f.png)

**Comment by mykle1** [comment]
I think this can just be added to the readme

**Comment by E3V3A** [comment]
PS. Note the weird text washout... (Is that your CSS ?)

**Comment by mykle1** [comment]
I doubt that my css has anything to do with that
