### ISSUE TITLE
Default top-center widget position covers top-left widgets

### ISSUE THREAD

**Issue by E3V3A** [mykle1/MMM-ISS#7]
For narrow screens, the top center widget covers some of the `top-left` widgets. 
What are the real widths here?

Seem to be `310 x 450 px`.

**Comment by mykle1** [comment]
More importantly, I have some css issues with the velocity and altitude that I am struggling with. I like their position in the module but moving them there caused other problems for the entire module

**Comment by E3V3A** [comment]
I'm starting to wonder if it is not just better to scrape the widget URL response so we have full control of the info?

**Comment by mykle1** [comment]
If you'd like to work on that then I will accept the PR. I would like it to retain some of the appearance of the widget
