### ISSUE TITLE
Add a very useful picture how to use the data provided

### ISSUE THREAD

**Issue by E3V3A** [mykle1/MMM-ISS#8]
I think people could benefit from seeing this picture:

![astro_horizon 1](https://user-images.githubusercontent.com/194392/36969128-45a7803e-206d-11e8-96dc-d1de33d977cc.png)

From here: https://spotthestation.nasa.gov/images/astro_horizon.png

**Comment by mykle1** [comment]
Yes, I've seen this picture and it is very informative. Where do you suggest I use it? In the readme?

**Comment by E3V3A** [comment]
README sound good.

**Comment by mykle1** [comment]
added
