### ISSUE TITLE
Alternative API for ISS passby

### ISSUE THREAD

**Issue by E3V3A** [mykle1/MMM-ISS#9]
Hi @mykle1  Did you see this?

* http://open-notify.org/
* http://open-notify.org/Open-Notify-API/ISS-Pass-Times/
* https://github.com/open-notify/Open-Notify-API
* http://justingosses.com/issflyover/

It provide you with a JSON return for any location... 
Perhaps useful for a more minimalistic version of your Module.

I find the returned iFrame take up a lot of space with unnecessary info, like my own city, links, images and other eye candy. So perhaps this could be an alternative? what do you think?

**Comment by mykle1** [comment]
I'm using "http://api.open-notify.org/iss-pass.json?. . . . " for velocity and altitude as you'll notice in the MMM-ISS.js file. My original version used more of the return from that source but I settled on the graphic version. Feel free to fork the repo and make any changes you like

**Comment by E3V3A** [comment]
IDK, how I missed that in your file. 

Anyway, I posted this issue. 
https://github.com/open-notify/Open-Notify-API/issues/20

Any idea why the rise times from their API is 20 min off from that provided by the spot-the-station?
